

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jesusisking

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: update

    show-sql: true
server:
  port: 9000


